In [3]:
import numpy as np

In [4]:
#casual array
python_list = [0,1,2,3,4,5]

In [5]:
array_from_list = np.array(python_list)

print(array_from_list)
print( type(array_from_list))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
array_from_list = np.array(python_list, dtype = float)

print(array_from_list)
print( type(array_from_list))

[0. 1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


In [7]:
array_from_list = np.array(python_list, dtype = bool)

print(array_from_list) #all numbers (maybe even words)* in list excepting 0 will be displayed as True
print( type(array_from_list))

[False  True  True  True  True  True]
<class 'numpy.ndarray'>


In [8]:
#dimensional array
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
two_dimensional_array = np.array(two_dimensional_list)
print(two_dimensional_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#Array -> list
array_from_list = np.array(python_list, dtype = int)
array_to_list = array_from_list.tolist()

print( type(array_to_list))
print("One dimensional list from array: ", array_to_list)
print("Two dimensional list from array", two_dimensional_array.tolist())


<class 'list'>
One dimensional list from array:  [0, 1, 2, 3, 4, 5]
Two dimensional list from array [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [12]:
#Shape of numpy (one dimensional array)
nums = np.array([1, 2, 3, 4, 5])
print(nums)
print('shape of nums: ', nums.shape)

[1 2 3 4 5]
shape of nums:  (5,)


In [11]:
#two dimensional array
numpy_two_dimensional_list = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list: ', numpy_two_dimensional_list.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list:  (3, 3)


In [14]:
# 3*4 array shape
three_by_four_array = np.array([[0, 1, 2, 3],
        [4,5,6,7],
        [8,9,10,11]])
print(three_by_four_array, "\n")
print(f"Shape: {three_by_four_array.shape}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Shape: (3, 4)


In [15]:
# "Size", number of items in whole array
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
two_dimensional_list = np.array([[0, 1, 2],
                              [3, 4, 5],
                              [6, 7, 8]])

print('The size:', numpy_array_from_list.size)
print('The size:', two_dimensional_list.size) 

The size: 5
The size: 9


In [ ]:
# Mathematical Operations

In [21]:
# Addition
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list, "+ 10")
ten_plus_original = numpy_array_from_list  + 10
print('result after addition: ', ten_plus_original)


original array:  [1 2 3 4 5] + 10
result after addition:  [11 12 13 14 15]


In [22]:
# Subtraction
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list, "- 10")
ten_minus_original = numpy_array_from_list  - 10
print('result of substraction: ', ten_minus_original)

original array:  [1 2 3 4 5] - 10
result of substraction:  [-9 -8 -7 -6 -5]


In [23]:
# Multiplication
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list, "* 10")
ten_times_original = numpy_array_from_list * 10
print('result of multiply: ', ten_times_original)

original array:  [1 2 3 4 5] * 10
result of multiply:  [10 20 30 40 50]


In [25]:
# Division
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list, "/ 10")
ten_times_original = numpy_array_from_list / 10
print('result of division: ', ten_times_original)

original array:  [1 2 3 4 5] / 10
result of division:  [0.1 0.2 0.3 0.4 0.5]


In [28]:
# Modulus; Finding the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list, '% 3')
ten_times_original = numpy_array_from_list % 3
print(ten_times_original)

original array:  [1 2 3 4 5] % 3
[1 2 0 1 2]


In [29]:
# Floor division: the division result without the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list, '// 10')
ten_times_original = numpy_array_from_list // 10
print(ten_times_original)

original array:  [1 2 3 4 5] // 10
[0 0 0 0 0]


In [30]:
# Exponential is finding some number the power of another:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list, '** 2')
ten_times_original = numpy_array_from_list  ** 2
print(ten_times_original)

original array:  [1 2 3 4 5] ** 2
[ 1  4  9 16 25]


In [31]:
# 2 Dimension Array
two_dimension_array = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(type (two_dimension_array))
print(two_dimension_array)
print('Shape: ', two_dimension_array.shape)
print('Size:', two_dimension_array.size)
print('Data type:', two_dimension_array.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Size: 9
Data type: int64


In [35]:
#Getting items from a numpy array
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)


first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('\nFirst column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)
print("\n", two_dimension_array)

First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]

First column: [1 4 7]
Second column: [2 5 8]
Third column:  [3 6 9]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
#Slicing Numpy array
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_two_rows_and_columns = two_dimension_array[0:2, 0:2]
print(first_two_rows_and_columns)

[[1 2]
 [4 5]]


In [39]:
#Reverse the row and column positions
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(two_dimension_array[::-1,::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [47]:
#How to represent missing values?
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
two_dimension_array[0, 0] = 55
two_dimension_array[1, 1] = 44
two_dimension_array[2, 2] = 33
print(two_dimension_array)

[[55  2  3]
 [ 4 44  6]
 [ 7  8 33]]


In [50]:
# Numpy Zeroes (np.zeros(), np.ones())
numpy_zeroes = np.zeros((3,3),dtype=int,order='C')
print(numpy_zeroes, '\n')

numpy_ones = np.ones((3,3),dtype=int,order='C')
print(numpy_ones, '\n')

twoes = numpy_ones * 2
print(twoes)

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[1 1 1]
 [1 1 1]
 [1 1 1]] 

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [58]:
# numpy.reshape()
first_shape  = np.array([(1,2,3), (4,5,6)])
print(f'FIRST SHAPE:\n{first_shape}\n')

second_shape= first_shape.reshape(3, 2)
print(f'SECOND SHAPE:\n{second_shape}\n')

#third_shape = second_shape.reshape (4, 4) CANNOT CAUSE SIZE IS 6 and 4*4 EQUAL 8!

FIRST SHAPE:
[[1 2 3]
 [4 5 6]]

SECOND SHAPE:
[[1 2]
 [3 4]
 [5 6]]



In [54]:
#numpy.flatten()
second_shape_flat = second_shape.flatten()
print(second_shape_flat)

[1 2 3 4 5 6]


In [6]:
#Horizontal(np.hstack()) and Vertical (np.vstack()) Stack of lists/arrays
import numpy as np
## Horizontal Stack
list_one = np.array([1,2,3])
list_two = np.array([4,5,6])

print("Casual addition operation causes: ", list_one + list_two)

print('Horizontal Append:', np.hstack((list_one, list_two)), '\n')

## Vertical Stack
print('Vertical Append:', np.vstack((list_one, list_two)))

Casual addition operation causes:  [5 7 9]
Horizontal Append: [1 2 3 4 5 6] 

Vertical Append: [[1 2 3]
 [4 5 6]]
